namespace PCHealth
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        
        static MainWindow Current{ get; };

        void PostMessageToWindow(String longMessage, String shortMessage, Boolean recursive);
    }
}
