namespace PCHealth
{
    [default_interface]
    runtimeclass SystemSearchViewer : Microsoft.UI.Xaml.Controls.UserControl
    {
        SystemSearchViewer();

        Windows.Foundation.IAsyncAction Search(String query);

        IObservableVector<String> Drives{ get; };
    }
}
